### ISSUE TITLE
Non-Sequence Variation description

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#104]
please review Non-sequence variation in future plans.
https://vr-spec.readthedocs.io/en/latest/appendices/future_plans.html#non-sequence-variation

**Comment by reece** [comment]
@larrybabb: I think you're referring to rules, which is covered by other issues. So, I'm going to remove this section from docs and close the issue. Please reopen if I'm mistaken.

**Comment by ahwagner** [comment]
I'm reopening–this is about things like gene expression and epigenetic modifications, involving molecular changes that are not changes to the residue sequence.

**Comment by reece** [comment]
I'm going to drop this from our v1 release. We can add this section when we have something substantial to describe.

**Comment by ahwagner** [comment]
That's fine. We do have examples of these variation types, but there is no harm in including these in a _future_ future directions. 😁
