### ISSUE TITLE
'Terminology and IM' page feedback

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#107]
https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/index.html

### Lead in Text: 

1. Regarding the following text:
> "Even for human interpretation, these definitions are inconsistent: does the definition describe a precise sequence change or a qualitative one"

It may not be clear to readers what you mean by a 'qualitative' change.

2. Regarding the following text:
> "We then translate each of these computational definitions into precise specifications for representing information (logical model)."

Do you use 'logical model' here to mean the same thing as 'information model'?  If so,  I would use this term - since that what you call this elsewhere. 
 
### Primitive Concepts:
I might include a line or two explaining what exactly you mean by 'Primitive Concept', 'Composite Concept', and how these are related. Not critical, but these terms will likely not be intuitively clear to everyone.
  
**Id:** 
1.  I think you should include some text about a recommendation to use CURIEs here (as you have in the json spec itself)?
 
**Residue:** 
1.  The computational definition of 'Residue' doesn’t sound like a definition, nor does it sound computational.  Consider updating def to be consistent with the tone/language used in other computational definitions, e.g. 'Sequence' (e.g. start the def for Residue with "a character or code representing a single monomeric unit of . . . ")

**Sequence:**

1. Why is Sequence the only Primitive concept with an Information model section in this document?  And the text in this IM section isn't really an information model - just a sentence that makes it sound like Sequence is a specialization of the string datatype.  

2. Related: Looking at the spec and the diagram, it is not clear if Sequence is meant to be a proper object in the model, with attributes of its own. Or just a specialization of the _string_ datatype (which seems to be the case for other primitives such as Id and Residue)

3. Regarding the following text: 
> "A Sequence provides a stable coordinate system by which an Allele may be located and interpreted. A Sequence may have several roles. A “reference sequence” is any Sequence used to define an Allele."

Here I might move the first sentence to follow from the second - which would let you be more precise about the fact that a Sequence with a "reference sequence" role is really what "provides a stable coordinate system by which an Allele may be located and interpreted".  This is not be true of a sequence with a "replacement sequence role".  Anyway, this is not critical, but something to consider because it speaks to a point of confusion raised at the Hinxton meeting.

4. Regarding the following text: 
> ". . . it is not necessary that Sequences be “typed” (i.e. DNA, RNA, or AA)"

This phrasing could be confusing - consider " it is not necessary that the molecular type of the sequence be explicitly represented (i.e. DNA, RNA, or AA)"

 
### Composite Concepts:
Generally, ensure consistency of the VR object graph diagram with the text and info models presented elsewhere in the documentation. 
- e.g. the 'type' for Location/SequenceLocation 'id' and 'sequence_id' attributes is CURIE in the diagram, and 'Id' in the IM table on the Location page.
- e.g. in the Variation box, the value of the id attribute is 'CURIE' . . . .CURIE isn't a defined type in the model - should the value be Id here? Or do you want to define CURIE as a data type in the documentation above?
  
Perhaps  there should be some info about CURIEs in the Implementation Guide section under Id . . . or at a least link to another page with this info?

**Comment by reece** [comment]
I *think* I captured the majority of these comments in changes, committing next. Thanks for the careful reading, @mbrush.
