### ISSUE TITLE
'Allele' page feedback

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#109]
https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/variation.html#allele

1. In the biological def: 

> “allele” refers to a set of specific changes within a Sequence. 

I am not sure I agree with this - but also not sure I understand what you mean by it.  If you mean to say that a common meaning for the term 'allele' is to refer to a **set** of discrete/discontinuous changes, I would disagree.  I think that 'allele' is generally used to refer to a contiguous span of sequence - which may include a single change, or multiple changes.  But the allele itself is a single, located, continuous span of sequence - not a set.

If however you mean that that "allele" refers to **one of a set of** specific variations of a sequence at a particular location, as per the Sequence Ontology definition, then I think this is ok, but should be clarified.

---------------

2. In the IM table, can you use SequenceState as the 'Type' for the state attribute? This would be more consistent with language in the doc that refers to the notion of a 'Sequence' as a component of an allele.  And I don’t think the other planned State subtypes (CNV state and  State Rule) are used to define alleles.

------------

3. For the text: 
> "The implementation MAY infer the Sequence by location_id and the Sequence State type, and ensure compatibility between them. This behavior is not included in the specification."

I don’t really follow your meaning here - in particular what "Sequence" means here (the Sequence State, or the reference sequence?)

------------

4. In the 'Notes' subsection, the following bullet repeats basically the same thing as written in the 'Implementation guidance' subsection:  
> "Alleles may have multiple representations on the same Sequence type due to shifting (aka shuffling, normalization). Fully resolving such equivalences is beyond the scope of the first phase of this specification."

------------

5. Can you link to the example code for Allele in the jupyter notebook, as you did for State (where you write "See example usage in the reference implementation documentation")?

**Comment by larrybabb** [comment]
@mbrush replying to...
2.  This is the discussion that was raised in the VR call today. Folks felt like they didn't want to be too precise with the typing of Allele.state and Allele.location to SequenceState and SequenceLocation, respectively.  The allele.type attribute is meant to be the type of the containing class, in this case 'Allele'.  We would have to change the "type" of state to SequenceState and likely the "type" of location to SequenceLocation to make this more precise as you suggest.  (i happen to agree with you, but folks felt like it would be easier to narrow this definition going forward versus expanding it in the event that other State or Location types emerge that may work for Allele. )

**Comment by reece** [comment]
Thanks @mbrush.

1. I wordsmithed Allele (the intention was your second guess, and I think we were missing a "one of" phrase).

2.  State here refers to the superclass, as does Location in the previous line. Allele could have states other than SequenceState (and will in the future).

3. We were just trying to say that the spec doesn't try to make sure that the kind of sequence (e.g., DNA) matches the kind of change made by the state (also DNA, one hopes). I reworded.

4. Good catch. Removed.

5. Will do in separate issue.

**Comment by ahwagner** [comment]
Reopening with related question.

Our specification [allows IUPAC ambiguity codes](https://vr-spec.readthedocs.io/en/1.0/terms_and_model.html#sequence) in `Sequence` objects, but our `Allele` calls for:
> a specific, single, and contiguous `Sequence` at a `Location (Abstract Class)`.

I think we should clarify what we mean by the use of "specific" here. Also, if IUPAC ambiguity is _not_ allowed under that definition of specific, we may want to consider narrowing the scope of Allele to `SequenceState` + `SequenceLocation`, instead of the abstract parent classes (I'm actually opposed to that idea, but just putting it out there as it would be logically consistent).

I would like to propose removing the notion of "specific" from the above definition, in line with the notion that Location and State are abstract concepts that may vary in (at least one definition of) specificity. This would also remove potential complications around the use of IUPAC ambiguity codes specifically in the context of `Allele.SequenceState.sequence`.

Thoughts from the group?

**Comment by reece** [comment]
I agree that "specific" is superfluous. Want to submit a PR for concrete discussion?

**Comment by reece** [comment]
Great. Thanks @ahwagner .

The Allele definition has a much larger problem: It refers to a Sequence, but the schema refers to a State. The definition wasn't updated when we changed the schema. :-(

I just added a commit to your 109 branch as a proposal to fix this.

**Comment by ahwagner** [comment]
Looks good. Added a new PR to address related concerns about the `State` definition.

**Comment by reece** [comment]
This issue appears to have been resolved in #177 .
