### ISSUE TITLE
'State' and 'Interval' pages feedback

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#110]
https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/state.html#state, and
https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/interval.html

Consider giving 'State' and 'Interval' biological definitions?  This could be clarifying for users - esp for the 'State' concept which is a bit ambiguous.

**Comment by larrybabb** [comment]
do you have a recommendation for how to define interval or state as biological?  It is my presumption that some of these data types are so elemental that they could span domains and be used in many use cases outside the scope of this specification. Interval is merely a Range in it's simplest form. There is not requirement to anchor it to biology.  State may be a candidate for a biological definition, depending on how abstract we really consider this data type.

**Comment by reece** [comment]
I agree with @larrybabb. Closing now. Let's reopen when there's a known problem with the definition and/or a proposal for text change.
