### ISSUE TITLE
'Location' page feedback

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#111]
https://vr-https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/location.html
 
Just a couple suggestions about wording the definitions to make the distinction and relationship between the concepts of Location and Sequence more clear and consistent.

1. As a biologist, I have concerns about language like the following from the computational definition, which makes Locations sound like they represent a region of sequence: 

>The Location abstract class refers to contiguous **regions** of biological sequences. Universally, a Location is an identifiable position or **region** on a Sequence.

Here, I suspect 'region' will likely be interpreted by many readers in the Sequence Ontology sense, which describes a **sequence** at a **location** (i.e. a vr:allele). This is problematic, because I think we need to be very clear that a Locations refer to an address, and not the sequence that occupies this address.  Language like the above is confusing in this regard.

I might suggest something like: _"The Location abstract class refers to the position in a genome that is occupied by a contiguous Sequence"_ - which more clearly distinguishes and relates the notion of a Location from that of the Sequence that resides at a Location. 
 
-------------

2. Similarly, language that treats terms like 'gene' or 'exon' of 'band' as if they are locations can also be confusing - as in the following sentence from the biological definition:

> As used by biologists, the precision of “location” (or “locus”) varies widely; examples include chromosomal bands, named genomic features (e.g., genes, exons, or markers), or specific positions on a reference sequence.

Here, I think that most biologists think of things like a 'gene' as the 'sequence feature' that is found at a Location - which, as a feature, can have functions, subsequences, etc.  Features like genes, exons, and chromosomal bands can be _used to infer a location_ when we can place them on a reference sequence - e.g. a 'gene location' can refer to the location where a gene is found in a genomic reference. But we should call this concept a 'gene location', or 'gene-based location' -  not a 'gene'.  

So for the passage above, I might consider something like: _"As used by biologists, the precision with which a “location” (or “locus”) is specified can vary widely; ranging from capture of precise start and end coordinates defining a Location, to references to named genomic features (e.g., chromosomal bands, genes, exons) as proxies for the Locations of these features on some reference genome."_

**Comment by reece** [comment]
Thanks Matt. I agree with your proposals and merged them (with some modification). Thanks!
