### ISSUE TITLE
SequenceLocation sequence_id

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#113]
The `sequence_id` field of `SequenceLocation` is of type `Id` [in the documentation](https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/location.html#sequencelocation) but is of type `string` in the [JSON Schema](https://github.com/ga4gh/vr-spec/blob/master/schema/vr.json#L100-L102).

I believe that it must be an `Id` (the [vr-python source](https://github.com/ga4gh/vr-python/blob/master/src/ga4gh/vr/_internal/computed_identifier.py#L69) provides such an example in the older `_`-delimited syntax), but the example notebook conflicts with this by [computing a digest on a SequenceLocation with a refseq `sequence_id`](https://vr-spec.readthedocs.io/en/latest/implementations/reference_implementation.html#serialize).

@reece, we should clarify how serialization works for values that _are not_ nested VR objects, and specifically resolve whether `sequence_id` is intended to be a digest (and thus enforced in code).

**Comment by ahwagner** [comment]
after speaking with @ronakypatel, we have decided that the use of computed ids in this field is preferable to treating aliases (e.g. refseq and ensembl identifiers for the same transcript sequence) as distinct.

I am going to update the JSON Schema to match the documentation in line with this decision. No changes will be made to vr-python implementation until @reece returns, leaving issue open until example from vr-python matches this as well.

**Comment by reece** [comment]
`sequence_id` is a string CURIE.

The recommended content is like `ga4gh:GS_0123acbd` (or whatever we resolve for ga4gh).
It may be `refseq:NM_01234.5` or `ensembl:ENST012345` or `GRCh38:1`. Namespaces are recommended to be from identifiers.org.

We could add `refget:xxxx` too. As Andy already mentioned, I think refget might migrate to base64url.  

Early versions of the spec strictly required using digest sequences. The mild but widespread feedback we received in the first two drafts was that people wanted the flexibility.

I'd like to keep the sequence_id as a CURIE for consistency and flexibility. I'm open to revisiting whether we require that they are digest sequences.

Yes, the location and allele digests depend on this choice. which is why it's so important that we nail down the CURIE format.

**Comment by ahwagner** [comment]
Thanks for getting back to us while away from office @reece, this input was very helpful!

We dropped the CURIE primitive a while ago, so I'm going to leave this as an `Id` type for now, which has the recommendation to use Computed Ids (which are, by definition, CURIE), but allows for the same flexibility provisions that were requested for other Ids.

Functionally (for @ronakypatel, myself, and other implementers), this answer is entirely sufficient for moving forward on implementation if we follow that recommendation (we are).

For the spec itself, we will want to consider if we want to:
a) attach additional provisions to this field (i.e. MUST be CURIE)
b) extend our computed ID requirements to encompass all fields of type `Id` (i.e. you can only create a computed id on a SequenceLocation if all the `Id` type fields are ga4gh.vr CURIEs)

**Comment by ronakypatel** [comment]
It is not straight forward to use cure in ids directly. I will put some info in the main issue.

**Comment by ahwagner** [comment]
@ronakypatel, could you elaborate on the challenges of using CURIEs for your implementation? The use of CURIEs is a huge benefit–it's what will allow implementations to know whether a passed `Id` is a ga4gh computed digest or an alternate string. We allow this flexibility for people to represent variants however they need to internally, but we REQUIRE that computed ids are based on ga4gh.vr computed ids in nested objects.

**Comment by ronakypatel** [comment]
@ahwagner There are no implementation challenges.

However, the CURIE are more meaning full in JSON-LD (really not sure about JSON). 

I have not looked extensively, but if you know some pointers that can help me understand use of **CURIE** in **JSON** would be very helpful.

For example:

{
  "@context": {
    "sequence_id": {
      "@id": "http://clinicalgenome.org/allele/sequence/",
      "@type": "@id"
    },
   "sequence_id": "NC_000012.9"
}

**Comment by ahwagner** [comment]
We discussed on Slack, but bringing this here for others reading this issue.

The use of CURIEs in `Id` type fields allows us to determine that the given id is valid for use in constructing computed ids of containing objects, a [requirement](https://github.com/ga4gh/vr-spec/blame/master/docs/source/specification/computed_identifiers/serialization.rst#L15-L16) of the specification.

This is necessary to provide the flexibility for other sequence identifiers to be used in these fields, a core requirement of the specification.

**Comment by reece** [comment]
That's correct: the spec requires that all ids are CURIEs. 
The example was supposed to be `refseq:NC_000012.9` but was copy-pasted from prior work (before the transition to CURIEs). 
I'll update the examples.

**Comment by reece** [comment]
@ronakypatel Updated in vr-python master
https://github.com/ga4gh/vr-python/blob/master/notebooks/Overview.ipynb
