### ISSUE TITLE
Normalization Image to RST

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#117]
Currently our description of the normalization algorithm uses an image to describe the process. We should convert to .rst and keep the doc structure consistent.

Thanks @cyenyxe!

**Comment by reece** [comment]
This comment

**Comment by reece** [comment]
The table is pretty heinous for inclusion in rst, but doable.
Before going that route, we should consider whether https://pypi.org/project/sphinxcontrib-excel-table/ could work.

**Comment by larrybabb** [comment]
I tried this on another project. It's a much better way to deal with large/complex tables. I would definitely use the sphinxcontrib-exel-table extension

**Comment by reece** [comment]
@larrybabb indicated an interested in tackling this. I've assigned to him to prevent others from working on the same issue.
