### ISSUE TITLE
Location Example should move to SequenceLocation

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#121]
The Example section in the abstract topic of Location would seem more consistent and appropriate if moved to the end of the SequenceLocation.  Location as an abstract concept does not yet have any fields defined and as such it seems premature or not appropriate to provide a specific sub-classes example in that section.

**Comment by larrybabb** [comment]
@reece I thought I'd make this one quick fix to help (a little). I committed to master which may not have been the proper approach based on the process we discussed. Please let me know or I can undo what I've done and stay out of the way.

**Comment by reece** [comment]
Thanks, Larry. This is a good move for now. I'm planning on revamping the examples and tests in the next week.

**Comment by reece** [comment]
Looks good! Done.
