### ISSUE TITLE
Incomplete / Incorrect VR prefixes?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#123]
I realize there's still some outstanding questions to answer regarding the prefixes in VR, but I think the list in the [Identifier Construction](https://vr-spec.readthedocs.io/en/1.0rc/algorithms/computed_identifier.html#identifier-construction) section should be as accurate and consistent with the 1.0 spec as possible.  

That said, I think VL - Location should be SL - Sequence Location, since it is likely that other Location types may arise.  Following the Variation subclasses all having a "V" in the first letter of the 2 letter prefix, it may make sense to do the same for Location and State since they are the other "identifiable" abstract types.  

I'm not sure adding "V" for all four identifiable abstract types is reasonable or forward thinking enough.

Finally, and minimally, we should add a prefix for the SequenceState identifiable class, since it can also presumably by digested and identified.

**Comment by reece** [comment]
I agree that the prefixes should be carefully thought out and that the table should say SL.

State isn't identifiable, so that doesn't have an identifier.

**Comment by larrybabb** [comment]
Good on SL.
@reece why is there an "id" on State if it is not identifiable? Is that an error. It is in the overview diagram and it the table of fields as well.

**Comment by reece** [comment]
See #139 and ga4gh/vr-python#31 in which the type prefixes were moved to the spec repo (specifically to https://github.com/ga4gh/vr-spec/blob/master/schema/ga4gh.yaml). This means that add/removes from the spec can be committed jointly with changes to the type prefixes.

Proposed policy re: type prefixes:

* Must be "reasonable" length, where reasonable means 2-4. In any case, we administer them
* Variation type prefixes begin with a V.
* Prefixes are for concrete identifiable types.
* The type-prefix map must be 1:1 (i.e., no degenerate mapping either direction)

@larrybabb @ahwagner: Comments?
