### ISSUE TITLE
Permitted Sequence for RNA molecules

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#124]
Do we want to add guidance (RECOMMEND) for the use of DNA codes in representing transcripts, as opposed to RNA codes? This is in line with EMBL and RefSeq practices for transcript sequence representation.

We currently REQUIRE only that IUPAC codes are used, which allows for the use of uracil.

**Comment by reece** [comment]
Our general guidance should be that Alleles must use the alphabet of the sequence used as reference.

Since all of the major transcript sources (esp RefSeq, Ensembl, LRG) use DNA for transcripts, this means that Alleles on transcript sequences should also use DNA.
