### ISSUE TITLE
Support and document guidance re: use of native identifiers

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#128]
https://docs.google.com/document/d/1TkgJMttPjKuAwc86B5x6jWw6HP-6waJyZmi7LFq5oYs/edit#heading=h.kozo07oghlnn

**Comment by reece** [comment]
The Required Data section now includes a statement that the data service will need to provide a mapping (actually, a multi-mapping) from GA4GH sequence ids to primary database ids. I will also implement this in VR Python (biocommons/vr-python#30).

**Comment by ahwagner** [comment]
add Python examples to required data section

**Comment by reece** [comment]
@ahwagner: Check out https://vr-spec.readthedocs.io/en/1.0rc/impl-guide/required_data.html#examples. If good, please close this issue.

**Comment by ahwagner** [comment]
Looks great! 👍
