### ISSUE TITLE
RFC: Do identifiable objects need an id attribute?

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#141]
As part of #127, the `id` attribute was removed because it is no longer needed by current implementations. However, some uses might need to store an identifier within a message. This issue is to collect use cases that require reviving an id attribute. Discussion should include why it needs to be a part of the VR schema itself as opposed to within a different schema. Note: Part of #127 is to adopt a convention to use a leading underscore to indicate attributes that are not part of the value object; therefore, an identifier attribute is likely to be called something like `_id`.

@larrybabb @rrfreimuth @cbizon

**Comment by larrybabb** [comment]
if we are treating the VR spec components as pure data types then I would say "no" to the need for an "id" property. But some (not all) of the concepts are "identifiable"  

If we do not want to support that notion or somehow remove the embedded ability to "id" the objects we call out as "identifiable" than we do not need it.  Or if we want to state that you can only reference one of these instances of identifiable data types via a _digest or via an inlined representation, then again, we do not need it.

However, it seems fairly reasonable to think that some implementers will define identifiers for them and use those identifiers to share and reference them with other systems without the need to inline.  I also think that implementers will need to annotate, extend and decorate these types in higher order constructs which may benefit from the ability to "id" the instances with any given implementers desired id system.

for global sharing the digest is best.  if we are convinced its so good that we should not allow for any others to id these objects, then we should not provide that option.

**Comment by larrybabb** [comment]
I think if we leave out the "id" for control by implementers, then we are essentially dictating that the "_digest" is the definitive (and only) way to id the object. If that is right, then we should simply state that and move forward.

**Comment by reece** [comment]
> for global sharing the digest is best

For global sharing, a computed identifier based on the digest is best. The digest alone is sufficient within a document, but should not be encouraged for global sharing.

As we ponder the question in this issue, we should also reevaluate the whether we should distinguish ids and identifiers as HL7 does.

**Comment by ahwagner** [comment]
This was a key concern of the PRC–having the ability to keep their own notation of, e.g. variant "name"–for usefulness.

**Comment by ahwagner** [comment]
We're keeping `_id`, and you can put any CURIE you want in there. Just don't compute VR identifiers on the element stored there unless it too is a VR identifier.
