### ISSUE TITLE
Write glossary definitions

### ISSUE THREAD

**Issue by helensch** [ga4gh/vr-spec#149]
https://vr-spec.readthedocs.io/en/master/appendices/glossary.html

**Comment by reece** [comment]
Doh! I thought that there was an outstanding issue to do this, but I was mistaken. I've renamed this issue to remind us to implement.

I will remove the glossary from master and preserve the modest skeleton in this issue.

[glossary.txt](https://github.com/ga4gh/vr-spec/files/3473836/glossary.txt)
