### ISSUE TITLE
VICC implementation examples

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#155]
@ahwagner I'm sure you are aware, but just verifying whether you will be updating the VICC implementation examples to show the VSL prefix for SequenceLocation and the change to include _digest and _id as optional attributes instead of the former "id" attribute?

**Comment by ahwagner** [comment]
Yes. Good to have an issue to track progress on that front anyway. Will leave open for that purpose.

**Comment by reece** [comment]
@ahwagner Do you intend to update the examples?
