### ISSUE TITLE
Replace _id and _digest with general underscore-prefix handling 

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#161]
The proposal is:
- drop _id and _digest from the schema since they exist purely as implementation conveniences (and are overly specific as well)
- permit *any* underscore-prefixed attribute. Use is implementation-defined. Underscore attributes are NOT included in digest serialization (as-is requirement).
- add new requirement that underscore attributes be excluded from messages

This would be very easy to implement and would allow us to drop _id and _digest from the information model, which I think makes sense.

**Comment by reece** [comment]
Two issues arose.

The most serious is that python-jsonschema-objects doesn't understand a patternProperty without a type. A type-less schema is valid (it means any type) and works elsewhere, but not with patternProperties. The consequence is that we would have to chose a single type for *all* patternProperties. 

The second issue is that I forgot that the presence of the _id attribute is the test for whether an object is identifiable, which in turn determines how its serialized. Removing it breaks serialization.

I'll keep this issue open for further consideration because @ahwagner and I both like the direction.

**Comment by ahwagner** [comment]
Based on discussions for responding to PRC feedback, we have opted to not go in this direction, and instead *DROP* `_digest` from the spec entirely. Closing for now, @reece feel free to reopen if we want to go in this direction as a v2 (breaking) change down the road.
