### ISSUE TITLE
Digest: probability of collision

### ISSUE THREAD

**Issue by rrfreimuth** [ga4gh/vr-spec#182]
In the appendix on [Truncated Digest Collision Analysis](https://vr-spec.readthedocs.io/en/1.0rc/appendices/truncated_digest_collision_analysis.html#collision-analysis), the number of bits given number of sequences (m) and probability of collision (P) is given as (sorry about the lack of formatting):

```
b(m, P) = \log_2{\left(\frac{m^2}{P}\right)} - 1
```

Farther down the page, in the code block that defines the function B, this formula is given:
```
b = math.log2(m / P) - 1
```

I think we're missing an exponent...
```
b = math.log2(m**2 / P) - 1
```

Am I missing something?

**Comment by reece** [comment]
Yikes. I think you're right.

I'll need a few days to get my head back into these weeds to double check.

Either way, thanks for the careful reading!

**Comment by rrfreimuth** [comment]
I'm working on a PR, will submit it shortly.
