### ISSUE TITLE
Implement Haplotypes

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#186]
There's been a lot of discussion about how to implement haplotypes and genotypes over the years. Alex, Larry, and Reece recently ratified a plan.

The tl;dr is that we'll proceed with the Haplotype and Genotype models from VMC, with the exception that we'll remove the partial option for the completeness flag for now.

We also considered other approaches, including VCF-style phase sets. We chose against this mostly because it merges the concepts of haplotype and genotype into a single structure, which is attractive but precludes well-scoped classes of the individual concepts.

**Comment by ahwagner** [comment]
After concerns raised on last week's call by @rrfreimuth, we have discussed the intent, purpose, and appropriateness of the `completeness` attribute in our `Haplotype` model. In review, we agreed that the use cases that this attribute covered was not worth the additional complexity in this class.

As a result, we've removed `completeness` from `Haplotype`. We currently are considering a preservation of the optional `location` in `Haplotype`, to allow users to explicitly describe the `Location` over which this `Haplotype` is defined. This allows us to construct precise messages of profiled region to the `Haplotype` object, but can also be omitted for simple message passing.

**Comment by rrfreimuth** [comment]
Thanks for the update!

We need to precisely define the semantics of `location` within the Haplotype class, especially if we allow it to be used for anything other than the outer bounds of the outer Alleles that comprise the Haplotype.

We also need to consider how the optionality of that attribute would impact the digest.  We cannot do this without first establishing the meaning of it, however.

**Comment by reece** [comment]
Also see comments in #33, which I'll now close so that this issue consolidates discussion.
