### ISSUE TITLE
namespace: ga4gh or vrs?

### ISSUE THREAD

**Issue by annalu12** [ga4gh/vr-spec#190]
My colleague Ian Fore raised a question about the CURIE namespace `ga4gh` belonging to other GA4GH workstreams. Does a vrs prefix namespace narrow the scope in the identifier here?
#https://github.com/ga4gh/vr-spec/blob/1598814955baeda62fe484b89bddaf70950cfd74/schema/ga4gh.yaml#L13

**Comment by reece** [comment]
@annalu12 , @ianfore 

We debated identifiers until we were all bruised an sore :-) in https://github.com/ga4gh/vr-spec/issues/32.

One of the considerations was whether the identifiers should be VRS-specific or GA4GH-wide. We decided that we wanted a GA4GH-wide standard to encourage interoperability within GA4GH, and, conversely, that we didn't want to bake GA4GH group names into the namespace. Also, some objects, like sequences now (and perhaps genes, etc later) transcend groups and need global scope.

So, we ended up proposing a GA4GH-wide identifier syntax to the Steering Committee and that was approved last September. [slides](https://docs.google.com/presentation/d/1yrzcmb_17K1ifq9y-5tWj31WVqcCYSZGgjbkYIdj_2o/edit).

So, that's a long way of saying that this decision is made and closed at this point.
