### ISSUE TITLE
Write up development process

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#195]
Alex, Larry, Bob, Reece want to provide a bit of structure around adding development process to VR. 

This is the proposal:

* Design. We'll talk about a design plan as leads, then in the group. This is the time to raise concerns about architectural directions. Architectural changes here are part of the game. The VR leads decide when a design is ready to transition to Coding.
* Coding. We'll check-in on development during coding. Challenges will be raised here. We might discover design problems too, in which case we go back to Design. Architectural changes here are unfortunate.
* Validation. Here we evaluate how well the implementation matches the design, documentation, tests, etc. Architecture changes here are expensive.

This roughly corresponds to columns on a kanban board: Design result = Backlog, Coding = In Progress, PR = QA+Done

**Comment by ahwagner** [comment]
Additional thoughts from Monday's call:

- A useful, earlier step before `Coding` might be `Verification`, where the Design decisions are reviewed and approved in entirety by the group. 
- One proposed mechanism for this was to create a branch linked to RTD and a corresponding Draft PR for review and discussion.
- The process decided on in this issue should be merged into our existing Development Process documentation.

**Comment by reece** [comment]
Let's keep the process as lightweight as possible, adding process steps only when we are certain that we have a problem and that the benefit merits the cost. 

"reviewed and approved by the entirety of the group" is a particularly daunting phrase. We then need to define what these terms mean (approved how? vote? and literally by the entirety of 70+ meeting invitees?)

In other words, I'd like to try the proposed process and add when we see an issue.
