### ISSUE TITLE
ChromosomeLocation and NamedInterval

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#210]
`ChromosomeLocation` requires the interval to be the concrete `NamedInterval` class, instead of the abstract `Interval`. While we don't want users using `SequenceInterval` with `ChromosomeLocation`, it is possible that other `Interval` subclasses emerge that we want to use for `ChromosomeLocation` (and in fact, there is at least one case I've run across so far to support this).

Opening issue to discuss this.

**Comment by reece** [comment]
The Interval class is not used anywhere right now and it serves no useful purpose in my mind. It should be deprecated and we can do so without any impacts. See #200.

My inclination is to create intervals that are specific to particular coordinate systems. For example, SequenceLocations use SequenceIntervals, which might have a variety of concrete interval representations that are relevant to sequences.

JSON Schema permits classes to belong to multiple abstractions, à la multiple inheritance.

**Comment by reece** [comment]
This was addressed in 0297dec. Closing.
