### ISSUE TITLE
Consider using json-ld instead of VMCBundle

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#26]
Tristan Nelson requested that we consider [json-ld](https://json-ld.org/) for the VMCBundle. Review this possibility for addition to or replacement of the current bundle.

**Comment by srynobio** [comment]
Also I think it's worth discussing if it's necessary.  I know the assertion modeling team were planning on using json-ld, but would it overly and unnecessarily complicate this model?

**Comment by reece** [comment]
VMC Bundle has been obsoleted, so the question is now moot. Closing.
