### ISSUE TITLE
Consider splitting 'Haplotype' into two subtypes

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#33]
This is a proposal to consider splitting 'Haplotype' into two subtypes - **one to represent the unlocated** haplotype (which is a discontinuous set of alleles), and **the other to represent the located** version (which is a continuous extent of sequence that contains some variation as part).

This idea that a Haplotype can be these two very different things depending on whether a Location is provided seems to be a point of confusion for many. In my opinion explicitly separating these in different classes **makes this distinction easier to explain and understand**, and would **allow more precise specification supporting haplotype creation in the schema**.  
We already do polymorphism so it can be implemented with no technical barriers.

Another proposed benefit is that this **would make mapping to classes in variation-related ontologies possible** (e.g. SO, GENO MSO).  Each of these ontologies make high level distinctions between sequences that are continuous features and things that are discontinuous sets, and thus they hold no classes that could map to the current VMC haplotype definition.  But if haplotype is split as proposed, then mappings could be made.   For example, the unlocated vmc haplotype would map directly to a GENO:haplotype (which it defines as a set of discontinuous alterations in cis), and the located vmc haplotype would map to a GENO:complex allele . . . as GENO, like the ClinVar allele model, distinguishes 'simple' alleles that vary along their entire extent, from 'complex' alleles that are defined extent's of sequence that contain variation(s) as a proper part).

The ability to map to ontology terms **would let us point to an ontological-based, high-level, biologically-rooted, conceptual model of the VMC domain of discourse**.  And perhaps more importantly,  it would make it **easy for people to understand how vmc concepts are related to variation concepts in other models that are also mapped in GENO** - as GENO would act as a Roseetta Stone allowing this translation. This would be a big win w.r.t. **interoperability with models in other communities** (e.g. model organism/AGR) who are at this time also working to define variation models to support their data, and considering use/alignment with GENO concepts.

@reece @larrybabb @ahwagner curious as to your thoughts here.

**Comment by reece** [comment]
This issue will be incorporated into #186 and closed.
