### ISSUE TITLE
How would Confidence Interval (CI) from VCF be included in VMC?

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#34]
Cristina Y. Gonzalez (EMBL-EBI) raised this question at the 7/16/2018 Var rep meeting (see minutes) which left the group leaning towards the notion that CI data should be external (like an annotation) on the primitive structures still under development for the core attributes/concepts needed to define the CNV.

We will need to demonstrate how the CI would be applied going forward to help all "see" how these type of fundamental and widely used qualifiers are applied to the VMC data in practice.

**Comment by reece** [comment]
The NestedInterval model has approximately the same information now for symmetric CIPOS and CIEND (i.e., -8,8). Now is a good time to consider generalizing to assymetric bounded intervals.
