### ISSUE TITLE
Questions about Feature-Based Locations

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#44]
Questions for Reece about the idea of Feature Based Locations (e.g. Gene Locations), as discussed on the 4-24-19 VA/VR call. I think this concept will be relevant for the Rule-Based Variation modeling work Larry, Alex, and I have been discussing. And more generally, I think getting on the same page here could be a catalyst for aligning our understanding and models more generally.  

The questions below are based on [this slide](https://docs.google.com/presentation/d/1KkYnmvD35-eVqPjdmfs9IhcmWuVysz93_A6hVqNsfJo/edit#slide=id.g50c60b5f18_0_266) - which I think is now out-of-date, but raises what I think will be informative questions regarding the evolution from this to the current model discussed n the 4-24-19 call.  Lots to unpack here - so we can discuss on a call/in person if that is easiest.
 
**Questions/Comments:**
1. I think what are called Positions on this slide were formerly called Intervals, and you are now calling Regions. Is this correct?
2. The Map Location type in the slide seems to include a specific assembly, but on the call today your model did not include this - to allow for a more generic model where tools can be provided to resolve a Map Location to a more precise Sequence Location based on a specific assembly.  
3. Is the Transcript Location type in the slide analogous to Sequence Location (but where the reference sequence is at the transcript level rather than genomic level)?   Or is it more analogous to Gene Location (but where the type of feature used as a proxy for a precise SequenceLocation is a Transcript/CDS rather than a Gene)?
     - The fact that the elements in Transcript Location include a transcript id and TranscriptPosition suggest the former. But in this case the 'projection' back to SequenceLocation  indicated by the arrows would be a different type of projection than for Gene Location (as for Transcripts you are starting with precise transcript-level coordinates and just mapping these to the genomic level).
4. Do you imagine the need for  other 'feature based location' subtypes based on feature types other than genes (e.g. CDS, Exon, Intron, Promoter, etc . . . ) - to allow reference to the generic location where any of these feature types exists?  Seems like the list of such feature types could get long.
5. Generally, I’d love to hear more about specific requirements/use cases around this level of modeling (Feature-Based Locations) from your perspective. I think you indicated on the call you had some informal models/proposals in this space.
 
. . . again, no need to respond initially here to all these points.  we can review next time we talk and document outcomes here if that is easiest.  Just wanted to record/share my thoughts while they are clear in my mind.

**Comment by reece** [comment]
This issue will be incorporated into #181 and closed.
