### ISSUE TITLE
Write specification for mosaic and chimeric genotypes

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#50]
Not that this is a priority, or even in scope - but just wanted to document this example as a new category of variation that is annotated in ClinVar.

**HGVS:** NM_000090.3(COL3A1):c.[=/3426_3452del27];[=/3440_3466del27]

**Description:** "Mosaic for two separate 27bp deletions in exon 48 in two cell strains of equal proportion"

**Link:** https://www.ncbi.nlm.nih.gov/clinvar/RCV000087646/

**Comment by reece** [comment]
See also this branch in hgvs: https://github.com/biocommons/hgvs/tree/104-complex-variants. It wasn't merged, but I think the basic premise of treating chimerism and mosaicism as properties of a genotype works. It doesn't capture the notion of "equal proportion" qualitatively or quantitatively.
