### ISSUE TITLE
Write specification @ readthedocs

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#53]
Transition the proposal section of the [draft document](https://docs.google.com/document/d/1tbGmw7cb1kozX3gwI_UdbsnS5Lf8BkcjVO9KdN96fTE/edit#heading=h.eg8ebx7l7qo) to a markdown format with references to spec.

**Comment by reece** [comment]
How will this be different from #19? If same, let's merge.

**Comment by ahwagner** [comment]
I think these are the same now, after the 5/13 VR call discussion. I'm going to close #19, since we're now focusing on writing from scratch instead of migrating the VMC docs.

**Comment by reece** [comment]
Okay. 

I think a new decision awaits: Do we want to use RTD at all?

RTD means using restructured text rather than md. RST is more powerful, but totally unnecessary as the spec is now envisioned.

Proposal: write markdown spec in (say) `spec/spec.md` in the vr-schema. (In subdir for images, etc.)

Thanks for writing!

**Comment by ljdursi** [comment]
RTD is based on Sphinx, which used to be rST-only but has allowed Markdown for a bit now - https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx

**Comment by reece** [comment]
@ljdursi Yep, I'm aware. As the markdown section says "Markdown doesn’t support a lot of the features of Sphinx".  Are you actually suggesting using Markdown in sphinx? If so, please explain the benefit because it's lost on me.

**Comment by ljdursi** [comment]
I’m just saying you can use markdown in RTD, and so have nicely formatted docs pages, since RTD does not mean rST necessarily.

   Jonathan

**Comment by ahwagner** [comment]
I think I'd like to have the spec on readthedocs. I'm not averse to using rST (or sphinx-MD as @ljdursi suggests) to write them, even if we're not utilizing auto-documentation or other cool sphinx features right away.

**Comment by reece** [comment]
@ahwagner: Looks to me that this can be closed. Please reopen if you intended more to happen on this issue.
