### ISSUE TITLE
Document driver project usage of vr schema

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#54]
- [x] VICC
- [x] ClinGen Allele Registry
- [x] BRCA Exchange

**Comment by ahwagner** [comment]
Blocked by https://github.com/biocommons/biocommons.seqrepo/issues/57

**Comment by cyenyxe** [comment]
The EGA/ENA/EVA driver project is not using it yet but planning to do so soon. Would you like to add these plans to the documentation, or to wait until it is actually implemented?

**Comment by ahwagner** [comment]
We should add in EGA/ENA/EVA to the 1.1 spec per @cyenyxe suggestion above, and we should update the BRCA Exchange Implementation text with examples (@melissacline is there a documentation page and/or query URLs we can link to)?

**Comment by melissacline** [comment]
Yes!  The data from BRCA Exchange can be queried at


http://brcaexchange-dev.gi.ucsc.edu/backend/data/variantreps/


This accesses a table of the variants from BRCA Exchange, translating
between systems of variant identification we're using (including internal
IDs) and VR.  Ambitiously, I'm working towards a Jupyter notebook to
describe using these data to sync with allele registry.  There are
technical issues to get through before this happens, but I'm working
towards going into the PRC meeting Tuesday morning with a description ready
of how this will happen.

**Comment by reece** [comment]
Fabulous! I appreciate your effort and progress!

Minor note: The ids are still using underscores rather than periods. Since you're using the vr-python reference implementation, fixing that might be as simple as updating the package.

**Comment by reece** [comment]
@ahwagner Ready to close?

**Comment by melissacline** [comment]
One last minute request, @Reece Hart <reecehart@gmail.com>, would you add a
reference to my paper under BRCA Exchange in Implementation?  Thanks!

Cline M.S., et al., *BRCA Challenge: BRCA Exchange as a global resource for
variants in BRCA1 and BRCA2." *PLoS Genet. 2018 Dec 26;14(12):e1007752.
doi:10.1371/journal.pgen.1007752
<https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007752>

**Comment by reece** [comment]
This is done. Closing.
