### ISSUE TITLE
Normalization - vt or custom?

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#60]
Hey @reece.

The VMC spec describes our normalization as both ["similar to the VT algorithm"](https://docs.google.com/document/d/12E8WbQlvfZWk5NrxwLytmympPby6vsv60RxCeD5wc1E/edit#heading=h.spi7f0i5bckv) and ["using the VT algorithm"](https://docs.google.com/document/d/12E8WbQlvfZWk5NrxwLytmympPby6vsv60RxCeD5wc1E/edit#heading=h.1zu9bgo96ipa). Which statement is more correct? And more to the point, will we be explicitly defining our own algorithm in the specification, or citing VT?

**Comment by reece** [comment]
Right now, it's right shifted as in the VMC spec.
I'm intending to implement NCBI's VOCA (used in SPDI), but haven't done so yet. I would *love* to have that as part of the spec.

**Comment by reece** [comment]
We will recommend fully-justified normalization. Draft text is in the current spec. doc.
Closing this issue (but leaving #70 open for now).
