### ISSUE TITLE
Generate schema doc from vr.yaml

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#61]
Using [sphinx-jsonschema](https://github.com/lnoor/sphinx-jsonschema) fails to work with our schema document (likely due to changes from `jsonchema v0.4`, which was used to develop the `sphinx-jsonschema` package). Look into programmatically reproducing this in rst with sphinx as a future enhancement.

**Comment by reece** [comment]
Yeah, I tried this ~2 months ago. I remember thinking it was a dead end. Lack of support for `oneOf` floats around my head behind a think fog, but I don't really recall for sure.

**Comment by ahwagner** [comment]
Yeah, I agree with that assessment. I think it would be useful down the road, but we'll probably have to roll our own sphinx extension to do it.

**Comment by reece** [comment]
I looked again at the sphinx-jsonschema extension as a way to synchronize the schema and docs.

The extension output is poorly formatted and doesn't handle the obvious things that we want, like inter-class links (which we currently can implement manually with .rst). (Technically, there is a way to generate such links, but it requires adding special tags to the json schema defs.)

So, I'm dropping this from 1.1. 

I think the way forward will be to implement a custom rst generator from the schema, then include that in the source tree.
