### ISSUE TITLE
finish drafting planned extensions

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#68]

**Comment by ahwagner** [comment]
@larrybabb I'll leave filling out the first draft of the "future plans" page to you.

**Comment by larrybabb** [comment]
it's filled in. I added specific issues for the sections that I did not feel comfortable drafting.

**Comment by larrybabb** [comment]
Leaving open until the following issues are closed:
#95  
#96 
#97 
#98 
#100
#101 
#102 
#103 
#104 
#105
