### ISSUE TITLE
Keep nested interval class in v1 spec?

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#76]

**Comment by ahwagner** [comment]
This documentation is complete, but leaving issue open as NestedIntervals (NIs) are not used by Alleles without a corresponding `State`. We should identify cases where NIs are used with SequenceState or remove this from the v1.0 submission.

@reece and other reviewers, please comment here with thoughts.

**Comment by larrybabb** [comment]
@ahwagner I'm not sure I understand 

>NestedIntervals (NIs) are not used by Alleles without a corresponding `State`.

Can add more information to help understand what the issue is?

I was under the impression that an Allele could have a SequenceLocation that was defined by either a Simple or NestedInterval depending on whether we wanted to express precise or ranged endpoints. and the ranged outer or inner endpoints could be fuzzy '?'.

Why is there any need to relate or define a dependency for the Interval classes on `State` or `SequenceState` ?

**Comment by ahwagner** [comment]
Thank you for asking. For reference, the current v1 classes and their relationships:

![object_graph](https://user-images.githubusercontent.com/811065/59038687-0cc10300-8839-11e9-8f54-2df3e75040af.png)

All of the components in this graph may be used to build valid `Variation` objects, except for `NestedInterval`. Why? Imagine a `SequenceLocation` _SL_ specified by a `NestedInterval`, which is then attached to an `Allele` _A_. What would the (required) `State` component of _A_ be? Currently, VR 1.0 only provides `SequenceState` as a `State` type. If you used a `SequenceState` _S_ to construct _A_, it would require interpreting the fixed-length _S_ of a variable-length _L_. It isn't intuitive to me what message would be conveyed by _A_ in this situation (I don't think this structure can convey any valid message).

Because `NestedInterval` cannot be used to construct a valid `Allele` with the available `State` components (AFAIK), I am proposing we drop it from the 1.0 specification. This is predicated on the belief that `Location` objects unusable by existing `Variation` subclasses are not valuable, which is why @reece proposed (and I agreed) to drop `CytobandLocation` and `GeneLocation` from the specification at an earlier stage.

Note that I want to keep `NestedInterval` in a future version of the specification, I'm only proposing that we delay until we can demonstrate its use in a `Variation`.

**Comment by reece** [comment]
I agree with @ahwagner that we should remove it.

I'm extremely sorry that we've pared the schema down so much, but he's right that it falls in the same category as CytobandLocation and GeneLocation.

**Comment by cyenyxe** [comment]
I also agree with dropping it from v1.0. Even though somewhat unfortunate, it will be much easier to get approved a small, 100% coherent schema, and release an increment every few months.

**Comment by larrybabb** [comment]
I've moved the NestedInterval section to the appendix for Future Plans accordingly.
We still need @reece to modify the images for the main composite concepts to remove it as well as turn it to yellow in the future plans image uml diagram.

**Comment by ahwagner** [comment]
@larrybabb I've been handling those images–won't be a problem to change. On it now.

**Comment by ahwagner** [comment]
@cyenyxe in response to your question (https://github.com/ga4gh/vr-spec/issues/76#issuecomment-499815544):

> Btw how do `NestedIntervals` relate with the imprecise locations in VCF? In that format, CIPOS and CIEND do not represent nesting but imprecision on both start and end.

They are meant to capture the same concept–the imprecision/fuzziness of endpoints. In the nested interval, there is an inner "certain" range and an outer "possible" range, but it still amounts to uncertainty at one or both ends of the outer range where it does not overlap the inner range.

I don't know if it's documented on GitHub anywhere, but we used to have 2 concepts, both the current inner/outer range model and a model that had a fuzzy start and end coordinate for both the start and end of a parent concept. I believe that the decision was made to select only one of the two systems, as they were deemed interchangeable. I wasn't part of that discussion, however–perhaps @rrfreimuth, @reece, or @larrybabb can provide additional detail to answer your question.
