### ISSUE TITLE
Revise statement on persisting IDs from remote systems

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#81]
From https://github.com/ga4gh/vr-spec/pull/78#issue-285434615, @cyenyxe asks:

>Receiving systems SHOULD NOT persist Ids from remote sources. Instead, Identifiers (below) SHOULD be used for communication between systems. -> MUST (NOT) instead of SHOULD (NOT)?

In my opinion this is a good change, but we will want to discuss as group prior to making change. Please comment with your own thoughts here, or react with 👍 / 👎 for making this change.

**Comment by larrybabb** [comment]
If our VR-schema is meant to support a messaging standard, similar to FHIR's specifications, then we may want to take a similar approach in the practice and guidance for the use of ids vs identifiers. I do think many folks will be using FHIR (at some point) at it seems to make sense to me. Plus, they have put considerable thought and energy and have years more experience with very broad groups of implementers on this topic specifically.

The "id" attribute on concepts shared in a message document are only required to be unique within the message. The only requirement is that the message receiver can use these values to correctly reconstruct the associations and structured message being received. It has no requirement that these ids are persistent or global, they can be transient. 

The "identifier" is aligned much closer to the concept of a business identifier. One that is likely immutable and persistent. One that can be used as a reference by external groups. One that is authored by a single authorizing agency and such.

Identifier values CAN be used for the value of an "id" on a concept in a message as it would be a very logical thing to do in satisfying the need to be able to uniquely reference the concepts in the message that are being digested.

If we combine these concepts or create constraints that make it impossible to separate these concepts then we will essentially be requiring everyone to use our digest as the ids for the purpose of sharing any of the VR concepts in any messages that they participate in. 

We should really be clear on whether we want to provide ANY guidance related to whether or not implementers SHOULD, SHOULD NOT, MUST or MUST NOT persist anything. Persistence implementation is outside of our guidance scope (IMO).

In the end, it may be best to remove this line completely from the spec as it appears to be out of scope and can only lead to lots of discussion and little value to any implementers.

(If some implementer wants to persist ids then what concern is that of ours. We could offer the computed digest identifier as a potential candidate for persisting and recalling concepts, but again this is likely outside the scope of our VR-Schema specification.)

**Comment by ahwagner** [comment]
We may want to add implementation guidance to computational identifiers section on the use of computational identifiers for the id field. tagging @reece
