### ISSUE TITLE
Bullet 6 rewrite on Primitive Concepts:Id:Implementation Guidance

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#82]
Line 74 o f [terms_and_model/index.rst](https://github.com/ga4gh/vr-spec/edit/master/docs/source/specification/terms_and_model/index.rst) states

>* Ids are not locatable references. An Id MAY NOT be used to retrieve objects from remote
  databases. Instead, Identifiers SHOULD be used for retrieval.

Shouldn't it state that `Ids are not intended to be locatable references` Would it be absolutely wrong to use a locatable identifier as an id?

Also, I'm not clear on whether the use of MAY NOT is covered by `RFC 2119`.  And why would we put a constraint in the spec to say that ids MAY NOT be used to retrieve objects from remote databases.

Finally, this seems to be the first appearance of the term `Identifers` in the last sentence. 

I feel as if this bullet should be rewritten or removed as it is not necessarily clear to a reader coming in for the first (or possibly subsequent times).  I'm not clear on it.

**Comment by ahwagner** [comment]
This is an artifact from when we had `Identifiers` in the spec... which we don't anymore. This was a recent change (see discussion at #56), and this reference to `Identifiers` should definitely go. Good catch!
