### ISSUE TITLE
Remove 'observation' from the Computational Definition of Variation

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#83]
@reece I think the first sentence in the Computational Definition of Variation SHOULD NOT have the term `observation` as a qualifier. I think it could be removed and still work. I intend to use these Variation data types for both Definitional and Observational purposes in practice. While this may be a minor point, the term `observation` has significant meaning in the HL7 circles and this could confuse the intended use of these data types.

Here's the sentence ...
[Variation Computational Definition](https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/variation.html)
>The Variation abstract class is the top-level object in the VR Schema Diagram and represents the concept of a molecular state observation.

**Comment by ahwagner** [comment]
Agreed, thank you for this. I know @reece was tagged, but I doubt he'd argue–I'm the one that wrote this section anyway.
