### ISSUE TITLE
Text.sequence should be changed

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#84]
I'm not sure if it was intentional to call the Text Variation string attribute `sequence` for the purpose of capturing Text Variation. The term sequence is used in several contexts for the data type and for various attributes related to capturing sequence of residues in a string format. 

I think it would be wise to change this to something like `value` or `display` or something that is not so closely coupled to sequence residue strings.

**Comment by ahwagner** [comment]
This was an error. Changed to match schema.
