### ISSUE TITLE
Clarify SequenceState computational definition

### ISSUE THREAD

**Issue by larrybabb** [ga4gh/vr-spec#86]
The first sentence of the `SequenceState` computational definition says

>The SequenceState class specifically captures Sequence changes over a defined Location. 

When the SequenceState is used within an `Allele` it would represent the sequence changes over a defined `Location`. But I do not see how `SequenceState` has any Location reference in and by itself.  Can we clarify this and/or correct this definition?

**Comment by ahwagner** [comment]
Agreed. As obvious as it sounds, I'm considering:

The *SequenceState* class specifically captures a *Sequence* as a *State*. This is the *State* class to use for representing "ref-alt" style variation, including SNVs, MNVs, del, ins, and delins.

**Comment by reece** [comment]
I agree with both of you. Merging.
